export const KEYWORD_ASSETS: Record<string, string[]> = {
  iran: ['CL', 'NATGAS', 'XAU', 'XAG'],
  oil: ['CL', 'NATGAS', 'XAU'],
  crude: ['CL', 'NATGAS'],
  fed: ['BTC', 'XAU', 'QQQ', 'ETH'],
  rates: ['BTC', 'XAU', 'QQQ', 'ETH'],
  inflation: ['XAU', 'BTC', 'QQQ'],
  election: ['TRUMP', 'QQQ', 'BTC'],
  trump: ['TRUMP', 'BTC', 'ETH'],
  ai: ['NVDA', 'FET', 'RENDER', 'TAO', 'VIRTUAL'],
  nvidia: ['NVDA', 'FET', 'RENDER'],
  gold: ['XAU', 'BTC'],
  silver: ['XAG', 'XAU'],
  recession: ['XAU', 'BTC', 'QQQ'],
  china: ['BTC', 'XAU', 'ETH'],
  tariff: ['QQQ', 'XAU', 'BTC'],
  bitcoin: ['BTC', 'ETH', 'SOL'],
  ethereum: ['ETH', 'LDO', 'SOL'],
  solana: ['SOL', 'JUP', 'RENDER', 'BONK'],
  meme: ['DOGE', '1000PEPE', 'BONK', 'FARTCOIN', 'TRUMP'],
  defi: ['AAVE', 'UNI', 'CRV', 'PENDLE', 'JUP'],
  gaming: ['AXS', 'GALA', 'YGG', 'IMX'],
  stocks: ['AAPL', 'TSLA', 'NVDA', 'META', 'GOOG', 'MSFT', 'AMZN'],
  tech: ['AAPL', 'NVDA', 'META', 'GOOG', 'MSFT', 'QQQ'],
  war: ['XAU', 'CL', 'BTC', 'NATGAS'],
  ukraine: ['XAU', 'CL', 'NATGAS', 'BTC'],
  russia: ['CL', 'NATGAS', 'XAU'],
  energy: ['CL', 'NATGAS'],
  crypto: ['BTC', 'ETH', 'SOL', 'DOGE'],
  layer2: ['ARB', 'OP', 'MATIC'],
};

export const SEARCH_CHIPS = [
  'Trending',
  'Oil',
  'Gold',
  'AI',
  'Elections',
  'Stocks',
  'Memes',
  'DeFi',
] as const;
