export interface PerpMarket {
  symbol: string;
  name: string;
  category: string;
  price: number;
  change24h: number;
  funding: number;
  maxLev: number;
  vol24h: number;
}

  export const ASTER_ALIASES: Record<string, string> = {
    'bitcoin': 'BTCUSDT',
  'btc': 'BTCUSDT',
  'ethereum': 'ETHUSDT',
  'eth': 'ETHUSDT',
  'solana': 'SOLUSDT',
  'sol': 'SOLUSDT',
  'bnb': 'BNBUSDT',
  'dogecoin': 'DOGEUSDT',
  'doge': 'DOGEUSDT',
  'hyperliquid': 'HYPEUSDT',
  'hype': 'HYPEUSDT',
  'chainlink': 'LINKUSDT',
  'link': 'LINKUSDT',
  'aave': 'AAVEUSDT',
  'uniswap': 'UNIUSDT',
  'uni': 'UNIUSDT',
  'maker': 'MKRUSDT',
  'mkr': 'MKRUSDT',
  'injective': 'INJUSDT',
  'inj': 'INJUSDT',
  'jupiter': 'JUPUSDT',
  'jup': 'JUPUSDT',
  'celestia': 'TIAUSDT',
  'tia': 'TIAUSDT',
  'rndr': 'RENDERUSDT',
  'render': 'RENDERUSDT',
  'arbitrum': 'ARBUSDT',
  'arb': 'ARBUSDT',
  'optimism': 'OPUSDT',
  'op': 'OPUSDT',
  'filecoin': 'FILUSDT',
  'fil': 'FILUSDT',
  'fantom': 'FTMUSDT',
  'ftm': 'FTMUSDT',
  'ripple': 'XRPUSDT',
  'xrp': 'XRPUSDT',
  'avalanche': 'AVAXUSDT',
  'avax': 'AVAXUSDT',
  'cardano': 'ADAUSDT',
  'ada': 'ADAUSDT',
  'polkadot': 'DOTUSDT',
  'dot': 'DOTUSDT',
  'litecoin': 'LTCUSDT',
  'ltc': 'LTCUSDT',
  'cosmos': 'ATOMUSDT',
  'atom': 'ATOMUSDT',
  'apple': 'AAPLUSDT',
  'aapl': 'AAPLUSDT',
  'tesla': 'TSLAUSDT',
  'tsla': 'TSLAUSDT',
  'nvidia': 'NVDAUSDT',
  'nvda': 'NVDAUSDT',
  'facebook': 'METAUSDT',
  'meta': 'METAUSDT',
  'google': 'GOOGUSDT',
  'alphabet': 'GOOGUSDT',
  'goog': 'GOOGUSDT',
  'microsoft': 'MSFTUSDT',
  'msft': 'MSFTUSDT',
  'amazon': 'AMZNUSDT',
  'amzn': 'AMZNUSDT',
  'nasdaq': 'QQQUSDT',
  'qqq': 'QQQUSDT',
  'robinhood': 'HOODUSDT',
  'hood': 'HOODUSDT',
  'intel': 'INTCUSDT',
  'intc': 'INTCUSDT',
  'micron': 'MUUSDT',
  'mu': 'MUUSDT',
  'sandisk': 'SNDKUSDT',
  'western digital': 'SNDKUSDT',
  'sndk': 'SNDKUSDT',
  'circle': 'CRCLUSDT',
  'crcl': 'CRCLUSDT',
  'south korea': 'EWYUSDT',
  'korea etf': 'EWYUSDT',
  'ewy': 'EWYUSDT',
  'gold': 'XAUUSDT',
  'xau': 'XAUUSDT',
  'silver': 'XAGUSDT',
  'xag': 'XAGUSDT',
  'copper': 'XCUUSDT',
  'xcu': 'XCUUSDT',
  'platinum': 'XPTUSDT',
  'xpt': 'XPTUSDT',
  'palladium': 'XPDUSDT',
  'xpd': 'XPDUSDT',
  'oil': 'CLUSDT',
  'crude': 'CLUSDT',
  'crude oil': 'CLUSDT',
  'cl': 'CLUSDT',
  'natural gas': 'NATGASUSDT',
  'natgas': 'NATGASUSDT',
  'paxos gold': 'PAXGUSDT',
  'paxg': 'PAXGUSDT',
  'aster': 'ASTERUSDT',
  'toncoin': 'TONUSDT',
  'ton': 'TONUSDT',
  'stellar': 'XLMUSDT',
  'xlm': 'XLMUSDT',
  'bitcoin cash': 'BCHUSDT',
  'bch': 'BCHUSDT',
  'zcash': 'ZECUSDT',
  'zec': 'ZECUSDT',
  'monero': 'XMRUSDT',
  'xmr': 'XMRUSDT',
  'tron': 'TRXUSDT',
  'trx': 'TRXUSDT',
  'dash': 'DASHUSDT',
  'ethereum classic': 'ETCUSDT',
  'etc': 'ETCUSDT',
  'internet computer': 'ICPUSDT',
  'icp': 'ICPUSDT',
  'hedera': 'HBARUSDT',
  'hbar': 'HBARUSDT',
  'stacks': 'STXUSDT',
  'stx': 'STXUSDT',
  'bittensor': 'TAOUSDT',
  'tao': 'TAOUSDT',
  'dogwifhat': 'WIFUSDT',
  'wif': 'WIFUSDT',
  'aptos': 'APTUSDT',
  'apt': 'APTUSDT',
  'sui': 'SUIUSDT',
  'near': 'NEARUSDT',
  'sei': 'SEIUSDT',
  'microstrategy': 'MSTRUSDT',
  'mstr': 'MSTRUSDT',
  'okb': 'OKBUSDT',
  'pancakeswap': 'CAKEUSDT',
  'cake': 'CAKEUSDT',
  'fetchai': 'FETUSDT',
  'fetch': 'FETUSDT',
  'fet': 'FETUSDT',
  'pendle': 'PENDLEUSDT',
  'curve': 'CRVUSDT',
  'crv': 'CRVUSDT',
  'lido': 'LDOUSDT',
  'ldo': 'LDOUSDT',
  'dydx': 'DYDXUSDT',
  'synthetix': 'SNXUSDT',
  'snx': 'SNXUSDT',
  'ethena': 'ENAUSDT',
  'ena': 'ENAUSDT',
  'ondo': 'ONDOUSDT',
  'eigenlayer': 'EIGENUSDT',
  'eigen': 'EIGENUSDT',
  'arweave': 'ARUSDT',
  'ar': 'ARUSDT',
  'berachain': 'BERAUSDT',
  'bera': 'BERAUSDT',
  'polygon': 'POLUSDT',
  'pol': 'POLUSDT',
  'worldcoin': 'WLDUSDT',
  'wld': 'WLDUSDT',
  'gala': 'GALAUSDT',
  'flow': 'FLOWUSDT',
  'pyth': 'PYTHUSDT',
  'kaspa': 'KASUSDT',
  'kas': 'KASUSDT',
  'virtuals': 'VIRTUALUSDT',
  'virtual': 'VIRTUALUSDT',
  'grass': 'GRASSUSDT',
  'zksync': 'ZKUSDT',
  'zk': 'ZKUSDT',
  'starknet': 'STRKUSDT',
  'strk': 'STRKUSDT',
  'axie': 'AXSUSDT',
  'axie infinity': 'AXSUSDT',
  'axs': 'AXSUSDT',
  'apecoin': 'APEUSDT',
  'ape': 'APEUSDT',
  'yield guild': 'YGGUSDT',
  'ygg': 'YGGUSDT',
  'jasmy': 'JASMYUSDT',
  'zilliqa': 'ZILUSDT',
  'zil': 'ZILUSDT',
  'oasis': 'ROSEUSDT',
  'rose': 'ROSEUSDT',
  'enjin': 'ENJUSDT',
  'enj': 'ENJUSDT',
  'story protocol': 'IPUSDT',
  'ip': 'IPUSDT',
  'magic eden': 'MEUSDT',
  'me': 'MEUSDT',
  'jito': 'JTOUSDT',
  'jto': 'JTOUSDT',
  'tensor': 'TNSRUSDT',
  'tnsr': 'TNSRUSDT',
  'cow protocol': 'COWUSDT',
  'cow': 'COWUSDT',
  'spx6900': 'SPXUSDT',
  'spx': 'SPXUSDT',
  'pudgy penguins': 'PENGUUSDT',
  'pengu': 'PENGUUSDT',
  'melania': 'MELANIAUSDT',
  'peanut': 'PNUTUSDT',
  'pnut': 'PNUTUSDT',
  'moo deng': 'MOODENGUSDT',
  'moodeng': 'MOODENGUSDT',
  'fartcoin': 'FARTCOINUSDT',
  'pump fun': 'PUMPUSDT',
  'pumpfun': 'PUMPUSDT',
  'pump': 'PUMPUSDT',
  };

  export const ASTER_LEVERAGE_LIMITS: Record<string, number> = {
    'BTCUSDT': 200,
  'ETHUSDT': 200,
  'SOLUSDT': 100,
  'ASTERUSDT': 200,
  'XRPUSDT': 75,
  'WLFIUSDT': 20,
  'BNBUSDT': 200,
  'XAGUSDT': 100,
  'DOGEUSDT': 75,
  'XAUUSDT': 75,
  'HYPEUSDT': 300,
  'CLUSDT': 50,
  'PIPPINUSDT': 25,
  'AVAXUSDT': 50,
  'TAOUSDT': 20,
  'CAKEUSDT': 25,
  'LTCUSDT': 50,
  'ETCUSDT': 50,
  'BULLAUSDT': 25,
  'LINKUSDT': 75,
  'DOTUSDT': 50,
  'QQQUSDT': 10,
  'SIRENUSDT': 20,
  'PUMPUSDT': 25,
  'TSLAUSDT': 10,
  'EDGEUSDT': 20,
  'ATOMUSDT': 50,
  'TRUMPUSDT': 50,
  'NEARUSDT': 50,
  'ZECUSDT': 50,
  'ADAUSDT': 50,
  'TRXUSDT': 50,
  'NVDAUSDT': 10,
  'AAVEUSDT': 25,
  'RIVERUSDT': 20,
  'SKYAIUSDT': 20,
  'GOOGUSDT': 10,
  'PAXGUSDT': 75,
  'SUIUSDT': 50,
  'UNIUSDT': 25,
  'FARTCOINUSDT': 25,
  'DAMUSDT': 20,
  'BARDUSDT': 20,
  'TAGUSDT': 20,
  'STBLUSDT': 20,
  '1000PEPEUSDT': 75,
  'NATGASUSDT': 10,
  'PIEVERSEUSDT': 20,
  'LYNUSDT': 20,
  'TOSHIUSDT': 25,
  'ZROUSDT': 20,
  'VVVUSDT': 20,
  'LITUSDT': 20,
  'XMRUSDT': 50,
  'AAPLUSDT': 10,
  'SKYUSDT': 20,
  '1000CHEEMSUSDT': 25,
  'SOONUSDT': 20,
  'EWYUSDT': 20,
  'XPLUSDT': 20,
  'AVNTUSDT': 20,
  'STABLEUSDT': 20,
  'FOLKSUSDT': 20,
  'FILUSDT': 25,
  'MSFTUSDT': 10,
  'BEATUSDT': 20,
  'SKRUSDT': 20,
  'XPTUSDT': 3,
  'LIGHTUSDT': 20,
  'TRUTHUSDT': 20,
  'ENSOUSDT': 20,
  'UAIUSDT': 20,
  'JCTUSDT': 20,
  'FETUSDT': 20,
  'XPINUSDT': 20,
  'CYSUSDT': 20,
  'BUSDT': 20,
  'GUNUSDT': 20,
  'LABUSDT': 20,
  'METAUSDT': 10,
  'TRIAUSDT': 20,
  'HUSDT': 20,
  'MONUSDT': 20,
  'DASHUSDT': 50,
  'SPKUSDT': 20,
  'ACUUSDT': 20,
  'PENGUUSDT': 25,
  'GWEIUSDT': 20,
  'ICPUSDT': 25,
  'CLANKERUSDT': 20,
  'AXSUSDT': 20,
  'FORMUSDT': 20,
  'POWERUSDT': 20,
  'ENAUSDT': 20,
  'INXUSDT': 20,
  'NAORISUSDT': 20,
  'INUSDT': 20,
  'TONUSDT': 50,
  'XLMUSDT': 25,
  'JELLYJELLYUSDT': 25,
  'SAHARAUSDT': 20,
  'RAVEUSDT': 20,
  'BANANAS31USDT': 25,
  'APTUSDT': 50,
  'BCHUSDT': 50,
  'XCUUSDT': 3,
  'BREVUSDT': 20,
  'KITEUSDT': 20,
  'AMZNUSDT': 10,
  'EVAAUSDT': 20,
  'ZAMAUSDT': 20,
  'BIOUSDT': 20,
  'SEIUSDT': 25,
  'INITUSDT': 20,
  'HEMIUSDT': 20,
  'BLUAIUSDT': 20,
  'INTCUSDT': 10,
  'SPXUSDT': 10,
  'OPNUSDT': 25,
  '0GUSDT': 20,
  'PIXELUSDT': 20,
  'DEXEUSDT': 20,
  'WETUSDT': 20,
  'BERAUSDT': 20,
  'POLUSDT': 20,
  'ANIMEUSDT': 20,
  'ENJUSDT': 20,
  'ARBUSDT': 50,
  'QUSDT': 20,
  'NIGHTUSDT': 20,
  'ONDOUSDT': 20,
  'BASUSDT': 20,
  'APRUSDT': 20,
  'USELESSUSDT': 20,
  'PHAUSDT': 20,
  'XPDUSDT': 3,
  'VANAUSDT': 20,
  'POLYXUSDT': 20,
  'TRADOORUSDT': 20,
  'APEUSDT': 20,
  'FLOCKUSDT': 5,
  'MYXUSDT': 20,
  'ZENUSDT': 20,
  'GIGGLEUSDT': 20,
  'COAIUSDT': 20,
  'GRASSUSDT': 20,
  'ZKPUSDT': 20,
  'ZKCUSDT': 20,
  'FOGOUSDT': 20,
  'SAPIENUSDT': 20,
  'KATUSDT': 25,
  'CCUSDT': 20,
  'SUSDT': 20,
  'JTOUSDT': 20,
  'LINEAUSDT': 20,
  'HOLOUSDT': 20,
  'ARIAUSDT': 20,
  'LDOUSDT': 20,
  'ARCUSDT': 20,
  'ATUSDT': 20,
  'WLDUSDT': 20,
  'HANAUSDT': 20,
  'GRIFFAINUSDT': 20,
  'BOBUSDT': 25,
  'BTRUSDT': 20,
  'FRAXUSDT': 20,
  'RENDERUSDT': 25,
  'INJUSDT': 25,
  'MOVEUSDT': 20,
  'DYMUSDT': 20,
  'UMAUSDT': 20,
  'IPUSDT': 20,
  'AIAUSDT': 20,
  'ESPUSDT': 20,
  'PTBUSDT': 20,
  'ROBOUSDT': 20,
  'MEUSDT': 20,
  'ZORAUSDT': 20,
  'JUPUSDT': 25,
  'DOLOUSDT': 20,
  'ELSAUSDT': 20,
  'RESOLVUSDT': 20,
  'ALLOUSDT': 20,
  'ETHFIUSDT': 20,
  'CYBERUSDT': 20,
  'DUSKUSDT': 20,
  '1000BONKUSDT': 25,
  'DEGOUSDT': 20,
  'KASUSDT': 20,
  'VIRTUALUSDT': 20,
  'AUCTIONUSDT': 20,
  'KGENUSDT': 20,
  'ZKUSDT': 20,
  'MMTUSDT': 20,
  'RPLUSDT': 20,
  'METUSDT': 20,
  'SOMIUSDT': 20,
  'OPUSDT': 50,
  'GALAUSDT': 20,
  'AIOUSDT': 20,
  'TURBOUSDT': 25,
  '1000SHIBUSDT': 50,
  'PENDLEUSDT': 20,
  'BMTUSDT': 20,
  'IRUSDT': 20,
  'MANTRAUSDT': 20,
  'MEGAUSDT': 25,
  'PENGUINUSDT': 25,
  'ZBTUSDT': 20,
  'AZTECUSDT': 20,
  'CRCLUSDT': 10,
  'SENTUSDT': 20,
  'GUAUSDT': 20,
  'PLAYUSDT': 20,
  'YBUSDT': 20,
  'ORCAUSDT': 20,
  'CLOUSDT': 20,
  'SPACEUSDT': 20,
  'COLLECTUSDT': 20,
  'FFUSDT': 20,
  'OGNUSDT': 20,
  'FUNUSDT': 20,
  'ALCHUSDT': 20,
  'TURTLEUSDT': 20,
  'XANUSDT': 20,
  'ROSEUSDT': 20,
  'YGGUSDT': 20,
  'MAGMAUSDT': 20,
  'LISTAUSDT': 20,
  'B2USDT': 20,
  'PYTHUSDT': 20,
  'CRVUSDT': 20,
  'PARTIUSDT': 20,
  'TOWNSUSDT': 20,
  'CFGUSDT': 20,
  'TRUSTUSDT': 20,
  'FLOWUSDT': 20,
  'ONUSDT': 20,
  'IRYSUSDT': 20,
  'MELANIAUSDT': 25,
  'XAIUSDT': 20,
  'SIGNUSDT': 20,
  'XNYUSDT': 20,
  'SOLVUSDT': 20,
  'BLESSUSDT': 20,
  'EIGENUSDT': 20,
  'ARPAUSDT': 20,
  'MSTRUSDT': 10,
  'SQDUSDT': 20,
  'LUNA2USDT': 20,
  'LAUSDT': 20,
  'ARUSDT': 50,
  'DYDXUSDT': 20,
  'EULUSDT': 20,
  'TIAUSDT': 25,
  'BANKUSDT': 20,
  'GMTUSDT': 20,
  'VELOUSDT': 20,
  'STGUSDT': 20,
  'UBUSDT': 20,
  'PNUTUSDT': 25,
  'GPSUSDT': 20,
  'SENTISUSDT': 20,
  'NOMUSDT': 20,
  'AXLUSDT': 20,
  'BIRBUSDT': 20,
  'MITOUSDT': 20,
  'HOODUSDT': 10,
  'OKBUSDT': 25,
  'STXUSDT': 25,
  'RECALLUSDT': 20,
  'FIGHTUSDT': 20,
  'STOUSDT': 20,
  'FHEUSDT': 20,
  'NEIROUSDT': 25,
  'STRKUSDT': 20,
  'HYPERUSDT': 50,
  'EDENUSDT': 20,
  '1000FLOKIUSDT': 25,
  'SNXUSDT': 20,
  'MOODENGUSDT': 25,
  'DOODUSDT': 25,
  'BOMEUSDT': 25,
  'MUUSDT': 3,
  'WHITEWHALEUSDT': 20,
  'SHELLUSDT': 20,
  'ACXUSDT': 20,
  'SNDKUSDT': 3,
  'BELUSDT': 20,
  'PROMPTUSDT': 20,
  'ZILUSDT': 20,
  'TAKEUSDT': 20,
  'BROCCOLI714USDT': 25,
  'ZEREBROUSDT': 25,
  'JASMYUSDT': 20,
  'COSUSDT': 20,
  'WARDUSDT': 20,
  'ARTXUSDT': 20,
  'PUMPBTCUSDT': 20,
  'AWEUSDT': 20,
  'MEMESUSDT': 20,
  'ESPORTSUSDT': 20,
  'PROVEUSDT': 20,
  'OPENUSDT': 20,
  'AVLUSDT': 20,
  'HBARUSDT': 25,
  'COWUSDT': 20,
  'TNSRUSDT': 20,
  'FLUXUSDT': 20,
  '1000LUNCUSDT': 25,
  'WIFUSDT': 25,
  'BONKUSDT': 25,
  'MKRUSDT': 25,
  'FTMUSDT': 25,
  };

  export type AsterCategory = 'crypto_major' | 'meme' | 'defi' | 'stock' | 'commodity' | 'political' | 'exchange_token';

  export const ASTER_CATEGORIES: Record<AsterCategory, { label: string; color: string }> = {
    crypto_major:   { label: "Crypto Major",    color: "#3B82F6" },
    meme:           { label: "Meme",            color: "#D4A574" },
    defi:           { label: "DeFi",            color: "#10B981" },
    stock:          { label: "Stock",           color: "#8B5CF6" },
    commodity:      { label: "Commodity",       color: "#D97706" },
    political:      { label: "Political",       color: "#EC4899" },
    exchange_token: { label: "Exchange Token",  color: "#6366F1" },
  };

  export const ASTER_MARKET_LIST: PerpMarket[] = [
  // CRYPTO MAJOR
  { symbol: "BTCUSDT",           name: "Bitcoin",           category: "crypto_major",      price: 0, change24h: 0, funding: 0, maxLev: 200, vol24h: 0 },
  { symbol: "ETHUSDT",           name: "Ethereum",          category: "crypto_major",      price: 0, change24h: 0, funding: 0, maxLev: 200, vol24h: 0 },
  { symbol: "SOLUSDT",           name: "Solana",            category: "crypto_major",      price: 0, change24h: 0, funding: 0, maxLev: 100, vol24h: 0 },
  { symbol: "XRPUSDT",           name: "XRP",               category: "crypto_major",      price: 0, change24h: 0, funding: 0, maxLev: 75,  vol24h: 0 },
  { symbol: "BNBUSDT",           name: "BNB",               category: "crypto_major",      price: 0, change24h: 0, funding: 0, maxLev: 200, vol24h: 0 },
  { symbol: "AVAXUSDT",          name: "Avalanche",         category: "crypto_major",      price: 0, change24h: 0, funding: 0, maxLev: 50,  vol24h: 0 },
  { symbol: "LTCUSDT",           name: "Litecoin",          category: "crypto_major",      price: 0, change24h: 0, funding: 0, maxLev: 50,  vol24h: 0 },
  { symbol: "ETCUSDT",           name: "Ethereum Classic",  category: "crypto_major",      price: 0, change24h: 0, funding: 0, maxLev: 50,  vol24h: 0 },
  { symbol: "DOTUSDT",           name: "Polkadot",          category: "crypto_major",      price: 0, change24h: 0, funding: 0, maxLev: 50,  vol24h: 0 },
  { symbol: "ATOMUSDT",          name: "Cosmos",            category: "crypto_major",      price: 0, change24h: 0, funding: 0, maxLev: 50,  vol24h: 0 },
  { symbol: "NEARUSDT",          name: "Near",              category: "crypto_major",      price: 0, change24h: 0, funding: 0, maxLev: 50,  vol24h: 0 },
  { symbol: "ZECUSDT",           name: "Zcash",             category: "crypto_major",      price: 0, change24h: 0, funding: 0, maxLev: 50,  vol24h: 0 },
  { symbol: "ADAUSDT",           name: "Cardano",           category: "crypto_major",      price: 0, change24h: 0, funding: 0, maxLev: 50,  vol24h: 0 },
  { symbol: "TRXUSDT",           name: "TRON",              category: "crypto_major",      price: 0, change24h: 0, funding: 0, maxLev: 50,  vol24h: 0 },
  { symbol: "SUIUSDT",           name: "Sui",               category: "crypto_major",      price: 0, change24h: 0, funding: 0, maxLev: 50,  vol24h: 0 },
  { symbol: "XMRUSDT",           name: "Monero",            category: "crypto_major",      price: 0, change24h: 0, funding: 0, maxLev: 50,  vol24h: 0 },
  { symbol: "DASHUSDT",          name: "Dash",              category: "crypto_major",      price: 0, change24h: 0, funding: 0, maxLev: 50,  vol24h: 0 },
  { symbol: "ICPUSDT",           name: "Internet Computer", category: "crypto_major",      price: 0, change24h: 0, funding: 0, maxLev: 25,  vol24h: 0 },
  { symbol: "TONUSDT",           name: "Toncoin",           category: "crypto_major",      price: 0, change24h: 0, funding: 0, maxLev: 50,  vol24h: 0 },
  { symbol: "XLMUSDT",           name: "Stellar",           category: "crypto_major",      price: 0, change24h: 0, funding: 0, maxLev: 25,  vol24h: 0 },
  { symbol: "APTUSDT",           name: "Aptos",             category: "crypto_major",      price: 0, change24h: 0, funding: 0, maxLev: 50,  vol24h: 0 },
  { symbol: "BCHUSDT",           name: "Bitcoin Cash",      category: "crypto_major",      price: 0, change24h: 0, funding: 0, maxLev: 50,  vol24h: 0 },
  { symbol: "ARUSDT",            name: "Arweave",           category: "crypto_major",      price: 0, change24h: 0, funding: 0, maxLev: 50,  vol24h: 0 },
  { symbol: "STXUSDT",           name: "Stacks",            category: "crypto_major",      price: 0, change24h: 0, funding: 0, maxLev: 25,  vol24h: 0 },
  { symbol: "HBARUSDT",          name: "Hedera",            category: "crypto_major",      price: 0, change24h: 0, funding: 0, maxLev: 25,  vol24h: 0 },

  // MEME
  { symbol: "DOGEUSDT",          name: "Dogecoin",          category: "meme",              price: 0, change24h: 0, funding: 0, maxLev: 75,  vol24h: 0 },
  { symbol: "PIPPINUSDT",        name: "Pippin",            category: "meme",              price: 0, change24h: 0, funding: 0, maxLev: 25,  vol24h: 0 },
  { symbol: "BULLAUSDT",         name: "Bulla",             category: "meme",              price: 0, change24h: 0, funding: 0, maxLev: 25,  vol24h: 0 },
  { symbol: "PUMPUSDT",          name: "Pump.fun",          category: "meme",              price: 0, change24h: 0, funding: 0, maxLev: 25,  vol24h: 0 },
  { symbol: "FARTCOINUSDT",      name: "Fartcoin",          category: "meme",              price: 0, change24h: 0, funding: 0, maxLev: 25,  vol24h: 0 },
  { symbol: "1000PEPEUSDT",      name: "Pepe",              category: "meme",              price: 0, change24h: 0, funding: 0, maxLev: 75,  vol24h: 0 },
  { symbol: "TOSHIUSDT",         name: "Toshi",             category: "meme",              price: 0, change24h: 0, funding: 0, maxLev: 25,  vol24h: 0 },
  { symbol: "1000CHEEMSUSDT",    name: "Cheems",            category: "meme",              price: 0, change24h: 0, funding: 0, maxLev: 25,  vol24h: 0 },
  { symbol: "PENGUUSDT",         name: "Pudgy Penguins",    category: "meme",              price: 0, change24h: 0, funding: 0, maxLev: 25,  vol24h: 0 },
  { symbol: "JELLYJELLYUSDT",    name: "JellyJelly",        category: "meme",              price: 0, change24h: 0, funding: 0, maxLev: 25,  vol24h: 0 },
  { symbol: "BANANAS31USDT",     name: "Bananas31",         category: "meme",              price: 0, change24h: 0, funding: 0, maxLev: 25,  vol24h: 0 },
  { symbol: "BOBUSDT",           name: "BOB",               category: "meme",              price: 0, change24h: 0, funding: 0, maxLev: 25,  vol24h: 0 },
  { symbol: "1000BONKUSDT",      name: "Bonk",              category: "meme",              price: 0, change24h: 0, funding: 0, maxLev: 25,  vol24h: 0 },
  { symbol: "TURBOUSDT",         name: "Turbo",             category: "meme",              price: 0, change24h: 0, funding: 0, maxLev: 25,  vol24h: 0 },
  { symbol: "1000SHIBUSDT",      name: "Shiba Inu",         category: "meme",              price: 0, change24h: 0, funding: 0, maxLev: 50,  vol24h: 0 },
  { symbol: "PENGUINUSDT",       name: "Penguin",           category: "meme",              price: 0, change24h: 0, funding: 0, maxLev: 25,  vol24h: 0 },
  { symbol: "MELANIAUSDT",       name: "Melania",           category: "meme",              price: 0, change24h: 0, funding: 0, maxLev: 25,  vol24h: 0 },
  { symbol: "PNUTUSDT",          name: "Peanut",            category: "meme",              price: 0, change24h: 0, funding: 0, maxLev: 25,  vol24h: 0 },
  { symbol: "NEIROUSDT",         name: "Neiro",             category: "meme",              price: 0, change24h: 0, funding: 0, maxLev: 25,  vol24h: 0 },
  { symbol: "1000FLOKIUSDT",     name: "Floki",             category: "meme",              price: 0, change24h: 0, funding: 0, maxLev: 25,  vol24h: 0 },
  { symbol: "MOODENGUSDT",       name: "Moo Deng",          category: "meme",              price: 0, change24h: 0, funding: 0, maxLev: 25,  vol24h: 0 },
  { symbol: "DOODUSDT",          name: "Doodles",           category: "meme",              price: 0, change24h: 0, funding: 0, maxLev: 25,  vol24h: 0 },
  { symbol: "BOMEUSDT",          name: "BOME",              category: "meme",              price: 0, change24h: 0, funding: 0, maxLev: 25,  vol24h: 0 },
  { symbol: "BROCCOLI714USDT",   name: "Broccoli",          category: "meme",              price: 0, change24h: 0, funding: 0, maxLev: 25,  vol24h: 0 },
  { symbol: "ZEREBROUSDT",       name: "Zerebro",           category: "meme",              price: 0, change24h: 0, funding: 0, maxLev: 25,  vol24h: 0 },
  { symbol: "1000LUNCUSDT",      name: "Luna Classic",      category: "meme",              price: 0, change24h: 0, funding: 0, maxLev: 25,  vol24h: 0 },
  { symbol: "WIFUSDT",           name: "dogwifhat",         category: "meme",              price: 0, change24h: 0, funding: 0, maxLev: 25,  vol24h: 0 },
  { symbol: "BONKUSDT",          name: "Bonk",              category: "meme",              price: 0, change24h: 0, funding: 0, maxLev: 25,  vol24h: 0 },

  // DEFI
  { symbol: "HYPEUSDT",          name: "Hyperliquid",       category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 300, vol24h: 0 },
  { symbol: "TAOUSDT",           name: "Bittensor",         category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "LINKUSDT",          name: "Chainlink",         category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 75,  vol24h: 0 },
  { symbol: "SIRENUSDT",         name: "Siren",             category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "EDGEUSDT",          name: "Edge",              category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "AAVEUSDT",          name: "Aave",              category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 25,  vol24h: 0 },
  { symbol: "RIVERUSDT",         name: "River",             category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "SKYAIUSDT",         name: "SkyAI",             category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "UNIUSDT",           name: "Uniswap",           category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 25,  vol24h: 0 },
  { symbol: "DAMUSDT",           name: "DAM",               category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "BARDUSDT",          name: "Bard",              category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "TAGUSDT",           name: "Tag",               category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "STBLUSDT",          name: "Stable",            category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "PIEVERSEUSDT",      name: "Pieverse",          category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "LYNUSDT",           name: "Lyn",               category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "ZROUSDT",           name: "LayerZero",         category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "VVVUSDT",           name: "VVV",               category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "LITUSDT",           name: "Lit",               category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "SKYUSDT",           name: "Sky",               category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "SOONUSDT",          name: "Soon",              category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "XPLUSDT",           name: "XPL",               category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "AVNTUSDT",          name: "Avant",             category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "STABLEUSDT",        name: "Stable",            category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "FOLKSUSDT",         name: "Folks",             category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "FILUSDT",           name: "Filecoin",          category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 25,  vol24h: 0 },
  { symbol: "BEATUSDT",          name: "Beat",              category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "SKRUSDT",           name: "Sekiro",            category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "LIGHTUSDT",         name: "Light",             category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "TRUTHUSDT",         name: "Truth",             category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "ENSOUSDT",          name: "Enso",              category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "UAIUSDT",           name: "UAI",               category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "JCTUSDT",           name: "JCT",               category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "FETUSDT",           name: "Fetch.ai",          category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "XPINUSDT",          name: "XPIN",              category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "CYSUSDT",           name: "Cysic",             category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "BUSDT",             name: "B Token",           category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "GUNUSDT",           name: "Gun",               category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "LABUSDT",           name: "Lab",               category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "TRIAUSDT",          name: "Tria",              category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "HUSDT",             name: "H Token",           category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "MONUSDT",           name: "Mon",               category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "SPKUSDT",           name: "Spark",             category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "ACUUSDT",           name: "Acu",               category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "GWEIUSDT",          name: "Gwei",              category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "CLANKERUSDT",       name: "Clanker",           category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "AXSUSDT",           name: "Axie Infinity",     category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "FORMUSDT",          name: "Form",              category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "POWERUSDT",         name: "Power",             category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "ENAUSDT",           name: "Ethena",            category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "INXUSDT",           name: "INX",               category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "NAORISUSDT",        name: "Naoris",            category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "INUSDT",            name: "IN Token",          category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "SAHARAUSDT",        name: "Sahara",            category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "RAVEUSDT",          name: "Rave",              category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "BREVUSDT",          name: "Brev",              category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "KITEUSDT",          name: "Kite",              category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "EVAAUSDT",          name: "EVAA",              category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "ZAMAUSDT",          name: "Zama",              category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "BIOUSDT",           name: "Bio Protocol",      category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "SEIUSDT",           name: "Sei",               category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 25,  vol24h: 0 },
  { symbol: "INITUSDT",          name: "Init",              category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "HEMIUSDT",          name: "Hemi",              category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "BLUAIUSDT",         name: "BluAI",             category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "0GUSDT",            name: "0G",                category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "PIXELUSDT",         name: "Pixel",             category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "DEXEUSDT",          name: "DeXe",              category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "WETUSDT",           name: "Wet",               category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "BERAUSDT",          name: "Berachain",         category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "POLUSDT",           name: "Polygon",           category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "ANIMEUSDT",         name: "Anime",             category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "ENJUSDT",           name: "Enjin",             category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "ARBUSDT",           name: "Arbitrum",          category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 50,  vol24h: 0 },
  { symbol: "QUSDT",             name: "Q Token",           category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "NIGHTUSDT",         name: "Night",             category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "ONDOUSDT",          name: "Ondo",              category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "BASUSDT",           name: "BAS",               category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "APRUSDT",           name: "APR",               category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "USELESSUSDT",       name: "Useless",           category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "PHAUSDT",           name: "Phala",             category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "VANAUSDT",          name: "Vana",              category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "POLYXUSDT",         name: "Polymesh",          category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "TRADOORUSDT",       name: "Tradoor",           category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "APEUSDT",           name: "ApeCoin",           category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "MYXUSDT",           name: "MYX",               category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "ZENUSDT",           name: "Horizen",           category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "GIGGLEUSDT",        name: "Giggle",            category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "COAIUSDT",          name: "CoAI",              category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "GRASSUSDT",         name: "Grass",             category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "ZKPUSDT",           name: "ZKP",               category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "ZKCUSDT",           name: "ZKC",               category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "FOGOUSDT",          name: "Fogo",              category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "SAPIENUSDT",        name: "Sapien",            category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "CCUSDT",            name: "CC",                category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "SUSDT",             name: "S Token",           category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "JTOUSDT",           name: "Jito",              category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "LINEAUSDT",         name: "Linea",             category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "HOLOUSDT",          name: "Holo",              category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "ARIAUSDT",          name: "Aria",              category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "LDOUSDT",           name: "Lido",              category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "ARCUSDT",           name: "Arc",               category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "ATUSDT",            name: "AT Token",          category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "WLDUSDT",           name: "Worldcoin",         category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "HANAUSDT",          name: "Hana",              category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "GRIFFAINUSDT",      name: "Griffain",          category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "BTRUSDT",           name: "Bitlayer",          category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "FRAXUSDT",          name: "Frax",              category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "RENDERUSDT",        name: "Render",            category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 25,  vol24h: 0 },
  { symbol: "INJUSDT",           name: "Injective",         category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 25,  vol24h: 0 },
  { symbol: "MOVEUSDT",          name: "Movement",          category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "DYMUSDT",           name: "Dymension",         category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "UMAUSDT",           name: "UMA",               category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "IPUSDT",            name: "Story Protocol",    category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "AIAUSDT",           name: "AIA",               category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "ESPUSDT",           name: "Espers",            category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "PTBUSDT",           name: "PTB",               category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "ROBOUSDT",          name: "Robo",              category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "MEUSDT",            name: "Magic Eden",        category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "ZORAUSDT",          name: "Zora",              category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "JUPUSDT",           name: "Jupiter",           category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 25,  vol24h: 0 },
  { symbol: "DOLOUSDT",          name: "Dolo",              category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "RESOLVUSDT",        name: "Resolv",            category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "ALLOUSDT",          name: "Allo",              category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "ETHFIUSDT",         name: "Ether.fi",          category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "CYBERUSDT",         name: "Cyber",             category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "DUSKUSDT",          name: "Dusk",              category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "DEGOUSDT",          name: "Dego",              category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "KASUSDT",           name: "Kaspa",             category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "VIRTUALUSDT",       name: "Virtuals",          category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "AUCTIONUSDT",       name: "Bounce",            category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "KGENUSDT",          name: "KGen",              category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "ZKUSDT",            name: "zkSync",            category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "MMTUSDT",           name: "MMT",               category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "RPLUSDT",           name: "Rocket Pool",       category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "METUSDT",           name: "MET",               category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "SOMIUSDT",          name: "Somi",              category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "OPUSDT",            name: "Optimism",          category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 50,  vol24h: 0 },
  { symbol: "GALAUSDT",          name: "Gala",              category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "AIOUSDT",           name: "AIO",               category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "PENDLEUSDT",        name: "Pendle",            category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "BMTUSDT",           name: "BMT",               category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "IRUSDT",            name: "IR",                category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "MANTRAUSDT",        name: "Mantra",            category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "ZBTUSDT",           name: "ZBT",               category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "AZTECUSDT",         name: "Aztec",             category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "SENTUSDT",          name: "Sentinel",          category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "GUAUSDT",           name: "Gua",               category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "PLAYUSDT",          name: "Play",              category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "YBUSDT",            name: "YB",                category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "ORCAUSDT",          name: "Orca",              category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "CLOUSDT",           name: "Clo",               category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "SPACEUSDT",         name: "Space",             category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "COLLECTUSDT",       name: "Collect",           category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "FFUSDT",            name: "FF",                category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "OGNUSDT",           name: "Origin",            category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "FUNUSDT",           name: "FunFair",           category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "ALCHUSDT",          name: "Alchemy",           category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "TURTLEUSDT",        name: "Turtle",            category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "XANUSDT",           name: "Xan",               category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "ROSEUSDT",          name: "Oasis",             category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "YGGUSDT",           name: "Yield Guild",       category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "MAGMAUSDT",         name: "Magma",             category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "LISTAUSDT",         name: "Lista",             category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "B2USDT",            name: "B2",                category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "PYTHUSDT",          name: "Pyth",              category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "CRVUSDT",           name: "Curve",             category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "PARTIUSDT",         name: "Parti",             category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "TOWNSUSDT",         name: "Towns",             category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "CFGUSDT",           name: "Centrifuge",        category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "TRUSTUSDT",         name: "Trust",             category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "FLOWUSDT",          name: "Flow",              category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "ONUSDT",            name: "ON",                category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "IRYSUSDT",          name: "Irys",              category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "XAIUSDT",           name: "XAI",               category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "SIGNUSDT",          name: "Sign",              category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "XNYUSDT",           name: "XNY",               category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "SOLVUSDT",          name: "Solv",              category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "BLESSUSDT",         name: "Bless",             category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "EIGENUSDT",         name: "EigenLayer",        category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "ARPAUSDT",          name: "ARPA",              category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "SQDUSDT",           name: "Subsquid",          category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "LUNA2USDT",         name: "Luna 2.0",          category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "LAUSDT",            name: "LA",                category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "DYDXUSDT",          name: "dYdX",              category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "EULUSDT",           name: "Euler",             category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "TIAUSDT",           name: "Celestia",          category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 25,  vol24h: 0 },
  { symbol: "BANKUSDT",          name: "Bank",              category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "GMTUSDT",           name: "STEPN",             category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "VELOUSDT",          name: "Velo",              category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "STGUSDT",           name: "Stargate",          category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "UBUSDT",            name: "UB",                category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "GPSUSDT",           name: "GPS",               category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "SENTISUSDT",        name: "Sentis",            category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "NOMUSDT",           name: "Nom",               category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "AXLUSDT",           name: "Axelar",            category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "BIRBUSDT",          name: "Birb",              category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "MITOUSDT",          name: "Mito",              category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "RECALLUSDT",        name: "Recall",            category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "FIGHTUSDT",         name: "Fight",             category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "STOUSDT",           name: "STO",               category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "FHEUSDT",           name: "FHE",               category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "STRKUSDT",          name: "Starknet",          category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "EDENUSDT",          name: "Eden",              category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "SNXUSDT",           name: "Synthetix",         category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "WHITEWHALEUSDT",    name: "WhiteWhale",        category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "SHELLUSDT",         name: "Shell",             category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "ACXUSDT",           name: "Across",            category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "BELUSDT",           name: "Bella",             category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "PROMPTUSDT",        name: "Prompt",            category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "ZILUSDT",           name: "Zilliqa",           category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "TAKEUSDT",          name: "Take",              category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "JASMYUSDT",         name: "Jasmy",             category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "COSUSDT",           name: "COS",               category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "WARDUSDT",          name: "Ward",              category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "ARTXUSDT",          name: "ARTX",              category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "PUMPBTCUSDT",       name: "PumpBTC",           category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "AWEUSDT",           name: "Awe",               category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "MEMESUSDT",         name: "Memes",             category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "ESPORTSUSDT",       name: "Esports",           category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "PROVEUSDT",         name: "Prove",             category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "OPENUSDT",          name: "Open",              category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "AVLUSDT",           name: "Avail",             category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "COWUSDT",           name: "CoW",               category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "TNSRUSDT",          name: "Tensor",            category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "FLUXUSDT",          name: "Flux",              category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "MKRUSDT",           name: "Maker",             category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 25,  vol24h: 0 },
  { symbol: "FTMUSDT",           name: "Fantom",            category: "defi",              price: 0, change24h: 0, funding: 0, maxLev: 25,  vol24h: 0 },

  // STOCK
  { symbol: "QQQUSDT",           name: "Nasdaq 100",        category: "stock",             price: 0, change24h: 0, funding: 0, maxLev: 10,  vol24h: 0 },
  { symbol: "TSLAUSDT",          name: "Tesla",             category: "stock",             price: 0, change24h: 0, funding: 0, maxLev: 10,  vol24h: 0 },
  { symbol: "NVDAUSDT",          name: "NVIDIA",            category: "stock",             price: 0, change24h: 0, funding: 0, maxLev: 10,  vol24h: 0 },
  { symbol: "GOOGUSDT",          name: "Alphabet",          category: "stock",             price: 0, change24h: 0, funding: 0, maxLev: 10,  vol24h: 0 },
  { symbol: "AAPLUSDT",          name: "Apple",             category: "stock",             price: 0, change24h: 0, funding: 0, maxLev: 10,  vol24h: 0 },
  { symbol: "EWYUSDT",           name: "S.Korea ETF",       category: "stock",             price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "MSFTUSDT",          name: "Microsoft",         category: "stock",             price: 0, change24h: 0, funding: 0, maxLev: 10,  vol24h: 0 },
  { symbol: "METAUSDT",          name: "Meta",              category: "stock",             price: 0, change24h: 0, funding: 0, maxLev: 10,  vol24h: 0 },
  { symbol: "AMZNUSDT",          name: "Amazon",            category: "stock",             price: 0, change24h: 0, funding: 0, maxLev: 10,  vol24h: 0 },
  { symbol: "INTCUSDT",          name: "Intel",             category: "stock",             price: 0, change24h: 0, funding: 0, maxLev: 10,  vol24h: 0 },
  { symbol: "SPXUSDT",           name: "SPX6900",           category: "stock",             price: 0, change24h: 0, funding: 0, maxLev: 10,  vol24h: 0 },
  { symbol: "CRCLUSDT",          name: "Circle",            category: "stock",             price: 0, change24h: 0, funding: 0, maxLev: 10,  vol24h: 0 },
  { symbol: "MSTRUSDT",          name: "MicroStrategy",     category: "stock",             price: 0, change24h: 0, funding: 0, maxLev: 10,  vol24h: 0 },
  { symbol: "HOODUSDT",          name: "Robinhood",         category: "stock",             price: 0, change24h: 0, funding: 0, maxLev: 10,  vol24h: 0 },
  { symbol: "MUUSDT",            name: "Micron",            category: "stock",             price: 0, change24h: 0, funding: 0, maxLev: 3,  vol24h: 0 },
  { symbol: "SNDKUSDT",          name: "Western Digital",   category: "stock",             price: 0, change24h: 0, funding: 0, maxLev: 3,  vol24h: 0 },

  // COMMODITY
  { symbol: "XAGUSDT",           name: "Silver",            category: "commodity",         price: 0, change24h: 0, funding: 0, maxLev: 100, vol24h: 0 },
  { symbol: "XAUUSDT",           name: "Gold",              category: "commodity",         price: 0, change24h: 0, funding: 0, maxLev: 75,  vol24h: 0 },
  { symbol: "CLUSDT",            name: "Crude Oil",         category: "commodity",         price: 0, change24h: 0, funding: 0, maxLev: 50,  vol24h: 0 },
  { symbol: "PAXGUSDT",          name: "Paxos Gold",        category: "commodity",         price: 0, change24h: 0, funding: 0, maxLev: 75,  vol24h: 0 },
  { symbol: "NATGASUSDT",        name: "Natural Gas",       category: "commodity",         price: 0, change24h: 0, funding: 0, maxLev: 10,  vol24h: 0 },
  { symbol: "XPTUSDT",           name: "Platinum",          category: "commodity",         price: 0, change24h: 0, funding: 0, maxLev: 3,  vol24h: 0 },
  { symbol: "XCUUSDT",           name: "Copper",            category: "commodity",         price: 0, change24h: 0, funding: 0, maxLev: 3,  vol24h: 0 },
  { symbol: "XPDUSDT",           name: "Palladium",         category: "commodity",         price: 0, change24h: 0, funding: 0, maxLev: 3,  vol24h: 0 },

  // POLITICAL
  { symbol: "WLFIUSDT",          name: "WLFI",              category: "political",         price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "TRUMPUSDT",         name: "Trump",             category: "political",         price: 0, change24h: 0, funding: 0, maxLev: 50,  vol24h: 0 },

  // EXCHANGE TOKEN
  { symbol: "ASTERUSDT",         name: "Aster",             category: "exchange_token",    price: 0, change24h: 0, funding: 0, maxLev: 200, vol24h: 0 },
  { symbol: "CAKEUSDT",          name: "PancakeSwap",       category: "exchange_token",    price: 0, change24h: 0, funding: 0, maxLev: 25,  vol24h: 0 },
  { symbol: "OPNUSDT",           name: "OPN",               category: "exchange_token",    price: 0, change24h: 0, funding: 0, maxLev: 25,  vol24h: 0 },
  { symbol: "FLOCKUSDT",         name: "Flock",             category: "exchange_token",    price: 0, change24h: 0, funding: 0, maxLev: 5,  vol24h: 0 },
  { symbol: "KATUSDT",           name: "KAT",               category: "exchange_token",    price: 0, change24h: 0, funding: 0, maxLev: 25,  vol24h: 0 },
  { symbol: "ELSAUSDT",          name: "Elsa",              category: "exchange_token",    price: 0, change24h: 0, funding: 0, maxLev: 20,  vol24h: 0 },
  { symbol: "MEGAUSDT",          name: "MEGA",              category: "exchange_token",    price: 0, change24h: 0, funding: 0, maxLev: 25,  vol24h: 0 },
  { symbol: "OKBUSDT",           name: "OKB",               category: "exchange_token",    price: 0, change24h: 0, funding: 0, maxLev: 25,  vol24h: 0 },
  { symbol: "HYPERUSDT",         name: "Hyper",             category: "exchange_token",    price: 0, change24h: 0, funding: 0, maxLev: 50,  vol24h: 0 },
  ];

  export function resolveAsterSymbolStatic(input: string): string | null {
    const normalized = input.toLowerCase().trim();
    if (ASTER_ALIASES[normalized]) return ASTER_ALIASES[normalized];
    const upper = input.toUpperCase().trim();
    if (upper.endsWith('USDT')) {
      const found = ASTER_MARKET_LIST.find(m => m.symbol === upper);
      if (found) return found.symbol;
    }
    const withSuffix = upper + 'USDT';
    const found = ASTER_MARKET_LIST.find(m => m.symbol === withSuffix);
    if (found) return found.symbol;
    return null;
  }

  export function getAsterMaxLeverage(symbol: string): number {
    return ASTER_LEVERAGE_LIMITS[symbol] || 25;
  }

  export function getAsterMarketsByCategory(category?: AsterCategory): PerpMarket[] {
    if (!category) return ASTER_MARKET_LIST;
    return ASTER_MARKET_LIST.filter(m => m.category === category);
  }

  export function getAsterSymbolFromPerp(symbol: string): string {
    return symbol.replace(/USDT$/, '');
  }
  