export type SectorKey =
  | "tech-mega"
  | "tech-growth"
  | "ai-quantum"
  | "cybersecurity"
  | "finance"
  | "crypto"
  | "healthcare"
  | "consumer"
  | "industrials"
  | "space"
  | "energy"
  | "mining"
  | "china-em"
  | "telecom"
  | "real-estate"
  | "semiconductors"
  | "index-etf"
  | "intl-etf"
  | "bond-etf"
  | "commodity-etf"
  | "infrastructure-etf"
  | "inverse-etf"
  | "other";

export interface SectorDef {
  key: SectorKey;
  emoji: string;
  label: string;
}

export const SECTORS: SectorDef[] = [
  { key: "tech-mega", emoji: "\u{1F5A5}", label: "Tech \u2014 Mega Cap" },
  { key: "tech-growth", emoji: "\u{1F680}", label: "Tech \u2014 Growth & Software" },
  { key: "ai-quantum", emoji: "\u{1F916}", label: "AI & Quantum Computing" },
  { key: "cybersecurity", emoji: "\u{1F512}", label: "Cybersecurity" },
  { key: "finance", emoji: "\u{1F4B0}", label: "Finance & Banking" },
  { key: "crypto", emoji: "\u{1FA99}", label: "Crypto & Digital Assets" },
  { key: "healthcare", emoji: "\u{1F3E5}", label: "Healthcare & Pharma" },
  { key: "consumer", emoji: "\u{1F6D2}", label: "Consumer & Retail" },
  { key: "industrials", emoji: "\u{1F3ED}", label: "Industrials & Defense" },
  { key: "space", emoji: "\u{1F6F0}", label: "Space & Aerospace" },
  { key: "energy", emoji: "\u26A1", label: "Energy & Utilities" },
  { key: "mining", emoji: "\u26CF", label: "Mining, Metals & Materials" },
  { key: "china-em", emoji: "\u{1F30F}", label: "China & Emerging Markets" },
  { key: "telecom", emoji: "\u{1F4E1}", label: "Telecom" },
  { key: "real-estate", emoji: "\u{1F3E0}", label: "Real Estate & REITs" },
  { key: "semiconductors", emoji: "\u{1F3E6}", label: "Semiconductors (ETF)" },
  { key: "index-etf", emoji: "\u{1F4CA}", label: "Broad Market Index ETFs" },
  { key: "intl-etf", emoji: "\u{1F30D}", label: "International & Regional ETFs" },
  { key: "bond-etf", emoji: "\u{1F4C8}", label: "Fixed Income & Bond ETFs" },
  { key: "commodity-etf", emoji: "\u{1F6E2}", label: "Commodity ETFs" },
  { key: "infrastructure-etf", emoji: "\u{1F3D7}", label: "Infrastructure & Thematic ETFs" },
  { key: "inverse-etf", emoji: "\u{1F4C9}", label: "Inverse & Leveraged ETFs" },
  { key: "other", emoji: "\u2753", label: "Other" },
];

export const SECTOR_MAP: Record<SectorKey, SectorDef> = Object.fromEntries(
  SECTORS.map(s => [s.key, s])
) as Record<SectorKey, SectorDef>;

const U: Record<string, SectorKey> = {
  AAPL: "tech-mega",
  NVDA: "tech-mega",
  MSFT: "tech-mega",
  GOOGL: "tech-mega",
  META: "tech-mega",
  AMZN: "tech-mega",
  AVGO: "tech-mega",
  TSLA: "tech-mega",
  ORCL: "tech-mega",
  CRM: "tech-mega",
  CSCO: "tech-mega",
  IBM: "tech-mega",
  INTC: "tech-mega",
  ACN: "tech-mega",
  ADBE: "tech-mega",
  TXN: "tech-mega",
  QCOM: "tech-mega",
  ASML: "tech-mega",
  LRCX: "tech-mega",
  KLAC: "tech-mega",
  ADI: "tech-mega",
  AMAT: "tech-mega",

  NFLX: "tech-growth",
  AMD: "tech-growth",
  PLTR: "tech-growth",
  APP: "tech-growth",
  NOW: "tech-growth",
  SHOP: "tech-growth",
  SNAP: "tech-growth",
  SPOT: "tech-growth",
  SNOW: "tech-growth",
  INTU: "tech-growth",
  ANET: "tech-growth",
  VRT: "tech-growth",
  CRWV: "tech-growth",
  FIG: "tech-growth",
  RDDT: "tech-growth",
  PINS: "tech-growth",
  DASH: "tech-growth",
  UBER: "tech-growth",
  PYPL: "tech-growth",
  OPRA: "tech-growth",
  GRAB: "tech-growth",
  MRVL: "tech-growth",
  ARM: "tech-growth",
  XYZ: "tech-growth",
  SNDK: "tech-growth",
  WDC: "tech-growth",
  STX: "tech-growth",
  COHR: "tech-growth",
  ON: "tech-growth",
  DIS: "tech-growth",

  SOUN: "ai-quantum",
  IONQ: "ai-quantum",
  QBTS: "ai-quantum",
  RGTI: "ai-quantum",
  QUBT: "ai-quantum",
  NBIS: "ai-quantum",
  BBAI: "ai-quantum",
  SOFI: "ai-quantum",
  SMCI: "ai-quantum",
  APLD: "ai-quantum",
  TSM: "ai-quantum",
  OKLO: "ai-quantum",

  CRWD: "cybersecurity",
  PANW: "cybersecurity",
  CIBR: "cybersecurity",

  "BRK.B": "finance",
  JPM: "finance",
  V: "finance",
  MA: "finance",
  GS: "finance",
  BAC: "finance",
  C: "finance",
  WFC: "finance",
  AXP: "finance",
  SCHW: "finance",
  BLK: "finance",
  COF: "finance",
  APO: "finance",
  SPGI: "finance",

  COIN: "crypto",
  MSTR: "crypto",
  HOOD: "crypto",
  MARA: "crypto",
  RIOT: "crypto",
  CIFR: "crypto",
  IREN: "crypto",
  BTBT: "crypto",
  BMNR: "crypto",
  BTGO: "crypto",
  CRCL: "crypto",
  AMBR: "crypto",
  WULF: "crypto",
  GLXY: "crypto",
  BLSH: "crypto",
  SBET: "crypto",
  EXOD: "crypto",
  IBIT: "crypto",
  ETHA: "crypto",
  FSOL: "crypto",
  TONX: "crypto",
  FIGR: "crypto",
  GRND: "crypto",
  HANMI: "financial",
  SAMSUNG: "tech",
  SKHYNIX: "tech",
  HYUNDAI: "auto",

  LLY: "healthcare",
  UNH: "healthcare",
  ABT: "healthcare",
  ABBV: "healthcare",
  JNJ: "healthcare",
  MRK: "healthcare",
  NVO: "healthcare",
  PFE: "healthcare",
  MDT: "healthcare",
  TMO: "healthcare",
  MRNA: "healthcare",
  VRTX: "healthcare",
  REGN: "healthcare",
  ISRG: "healthcare",
  HIMS: "healthcare",
  CAPR: "healthcare",
  ENLV: "healthcare",
  OSCR: "healthcare",
  AZN: "healthcare",
  AMGN: "healthcare",

  WMT: "consumer",
  KO: "consumer",
  PEP: "consumer",
  PG: "consumer",
  MCD: "consumer",
  CMCSA: "consumer",
  SBUX: "consumer",
  NKE: "consumer",
  COST: "consumer",
  CMG: "consumer",
  HD: "consumer",
  LOW: "consumer",
  CVNA: "consumer",
  PM: "consumer",
  AMC: "consumer",
  GME: "consumer",
  F: "consumer",

  HON: "industrials",
  LIN: "industrials",
  DHR: "industrials",
  LMT: "industrials",
  NOC: "industrials",
  RTX: "industrials",
  BA: "industrials",
  CAT: "industrials",
  DE: "industrials",
  GE: "industrials",
  GEV: "industrials",
  ETN: "industrials",
  MTZ: "industrials",
  UNP: "industrials",
  WM: "industrials",
  ITA: "industrials",
  AAL: "industrials",
  RIVN: "industrials",

  RKLB: "space",
  ASTS: "space",
  ACHR: "space",
  LUNR: "space",
  RDW: "space",
  GEMI: "space",

  XOM: "energy",
  CVX: "energy",
  COP: "energy",
  OXY: "energy",
  NEE: "energy",
  VST: "energy",
  TLN: "energy",
  CEG: "energy",
  PCG: "energy",
  SO: "energy",
  ENPH: "energy",
  SEDG: "energy",
  PLUG: "energy",
  PBR: "energy",

  GLD: "mining",
  SLV: "mining",
  PALL: "mining",
  PPLT: "mining",
  COPX: "mining",
  FCX: "mining",
  SCCO: "mining",
  NEM: "mining",
  ALB: "mining",
  MP: "mining",
  UEC: "mining",
  DNN: "mining",
  BTG: "mining",
  IAU: "mining",
  GLTR: "mining",
  FGDL: "mining",
  REMX: "mining",
  NIKL: "mining",
  URA: "mining",

  BABA: "china-em",
  BIDU: "china-em",
  BILI: "china-em",
  JD: "china-em",
  NIO: "china-em",
  LI: "china-em",
  PDD: "china-em",
  BZ: "china-em",
  NTES: "china-em",
  TCOM: "china-em",
  FUTU: "china-em",
  CPNG: "china-em",
  MELI: "china-em",
  VFS: "china-em",
  TM: "china-em",
  KWEB: "china-em",
  FXI: "china-em",
  ONDS: "other",

  T: "telecom",
  VZ: "telecom",
  TMUS: "telecom",

  EQIX: "real-estate",
  ABNB: "real-estate",
  VNQ: "real-estate",

  SOXX: "semiconductors",

  SPY: "index-etf",
  QQQ: "index-etf",
  TQQQ: "index-etf",
  IWM: "index-etf",
  IJR: "index-etf",
  VT: "index-etf",
  VTI: "index-etf",
  IVV: "index-etf",
  ITOT: "index-etf",
  IJH: "index-etf",
  IWN: "index-etf",
  IWF: "index-etf",
  VTV: "index-etf",
  FLQL: "index-etf",
  FFOG: "index-etf",
  INCE: "bond-etf",

  IEMG: "intl-etf",
  SCHF: "intl-etf",
  EEM: "intl-etf",
  EFA: "intl-etf",
  IEFA: "intl-etf",
  EWY: "intl-etf",
  EWJ: "intl-etf",
  EWZ: "intl-etf",
  ECH: "intl-etf",
  INDA: "intl-etf",

  TLT: "bond-etf",
  IEF: "bond-etf",
  SHY: "bond-etf",
  SGOV: "bond-etf",
  AGG: "bond-etf",
  HYG: "bond-etf",
  HYS: "bond-etf",
  TIP: "bond-etf",
  USFR: "bond-etf",
  FLHY: "bond-etf",
  BINC: "bond-etf",
  CLOI: "bond-etf",
  JAAA: "bond-etf",

  USO: "commodity-etf",
  BNO: "commodity-etf",
  UNG: "commodity-etf",
  PDBC: "commodity-etf",
  DBC: "commodity-etf",
  FTGC: "commodity-etf",
  OIH: "commodity-etf",

  PAVE: "infrastructure-etf",
  DGRW: "infrastructure-etf",

  SQQQ: "inverse-etf",
  PSQ: "inverse-etf",

  DFDV: "other",
  KRAQ: "other",
  OPEN: "other",
  TBLL: "other",
  MU: "tech-mega",
};

export function getSector(underlying: string): SectorKey {
  return U[underlying] || "other";
}
