export const ONDO_CATALOGUE: { symbol: string; name: string; underlying: string; price: string }[] = [
  { symbol: "MUON", name: "Micron Technology", underlying: "MU", price: "$425.93" },
  { symbol: "PDDON", name: "PDD Holdings", underlying: "PDD", price: "$96.63" },
  { symbol: "SQQQON", name: "ProShares UltraPro Short QQQ", underlying: "SQQQ", price: "$78.46" },
  { symbol: "SMCION", name: "Super Micro Computer", underlying: "SMCI", price: "$20.90" },
  { symbol: "TSMON", name: "Taiwan Semiconductor Manufacturing", underlying: "TSM", price: "$332.23" },
  { symbol: "USOON", name: "United States Oil Fund", underlying: "USO", price: "$119.55" },
  { symbol: "CEGON", name: "Constellation Energy", underlying: "CEG", price: "$286.60" },
  { symbol: "RKLBON", name: "Rocket Lab", underlying: "RKLB", price: "$68.21" },
  { symbol: "OXYON", name: "Occidental Petroleum", underlying: "OXY", price: "$61.05" },
  { symbol: "IEFAON", name: "iShares Core MSCI EAFE ETF", underlying: "IEFA", price: "$88.71" },
  { symbol: "EWYON", name: "iShares MSCI South Korea ETF", underlying: "EWY", price: "$128.15" },
  { symbol: "IAUON", name: "iShares Gold Trust", underlying: "IAU", price: "$84.58" },
  { symbol: "VSTON", name: "Vistra", underlying: "VST", price: "$149.66" },
  { symbol: "BBAION", name: "BigBear.ai Holdings", underlying: "BBAI", price: "$3.59" },
  { symbol: "ADBEON", name: "Adobe", underlying: "ADBE", price: "$249.28" },
  { symbol: "REMXON", name: "VanEck Rare Earth and Strategic Metals ETF", underlying: "REMX", price: "$79.11" },
  { symbol: "COPON", name: "ConocoPhillips", underlying: "COP", price: "$127.75" },
  { symbol: "MELION", name: "MercadoLibre", underlying: "MELI", price: "$1,652.63" },
  { symbol: "SBETON", name: "SharpLink Gaming, Inc", underlying: "SBET", price: "$7.41" },
  { symbol: "AMATON", name: "Applied Materials", underlying: "AMAT", price: "$356.50" },
  { symbol: "VRTON", name: "Vertiv", underlying: "VRT", price: "$258.62" },
  { symbol: "BABAON", name: "Alibaba", underlying: "BABA", price: "$123.55" },
  { symbol: "SNDKON", name: "SanDisk", underlying: "SNDK", price: "$716.40" },
  { symbol: "AALON", name: "American Airlines Group", underlying: "AAL", price: "$10.62" },
  { symbol: "UNGON", name: "US Natural Gas Fund", underlying: "UNG", price: "$12.36" },
  { symbol: "ONDSON", name: "Ondas Holdings", underlying: "ONDS", price: "$10.15" },
  { symbol: "FIGRON", name: "Figure Technology Solutions", underlying: "FIGR", price: "$34.14" },
  { symbol: "EEMON", name: "iShares MSCI Emerging Markets ETF", underlying: "EEM", price: "$56.90" },
  { symbol: "EFAON", name: "iShares MSCI EAFE ETF", underlying: "EFA", price: "$95.52" },
  { symbol: "TLTON", name: "iShares 20+ Year Treasury Bond ETF", underlying: "TLT", price: "$88.31" },
  { symbol: "RIOTON", name: "Riot Platforms", underlying: "RIOT", price: "$13.41" },
  { symbol: "RDWON", name: "Redwire", underlying: "RDW", price: "$9.07" },
  { symbol: "PSQON", name: "ProShares Short QQQ", underlying: "PSQ", price: "$31.74" },
  { symbol: "PANWON", name: "Palo Alto Networks", underlying: "PANW", price: "$163.75" },
  { symbol: "MARAON", name: "MARA Holdings", underlying: "MARA", price: "$8.49" },
  { symbol: "IRENON", name: "IREN", underlying: "IREN", price: "$41.63" },
  { symbol: "ASMLON", name: "ASML Holding NV", underlying: "ASML", price: "$1,327.23" },
  { symbol: "PDBCON", name: "Invesco Optimum Yld Dvsfd Cmd Str No K-1 ETF", underlying: "PDBC", price: "$17.31" },
  { symbol: "LRCXON", name: "Lam Research", underlying: "LRCX", price: "$228.63" },
  { symbol: "NOWON", name: "ServiceNow", underlying: "NOW", price: "$557.11" },
  { symbol: "BNOON", name: "US Brent Oil Fund", underlying: "BNO", price: "$52.34" },
  { symbol: "JDON", name: "JD.com", underlying: "JD", price: "$27.36" },
  { symbol: "PYPLON", name: "PayPal", underlying: "PYPL", price: "$44.40" },
  { symbol: "DNNON", name: "Denison Mines", underlying: "DNN", price: "$3.34" },
  { symbol: "DISON", name: "Disney", underlying: "DIS", price: "$100.57" },
  { symbol: "FIGON", name: "Figma Ord Shs", underlying: "FIG", price: "$23.66" },
  { symbol: "PBRON", name: "Petrobras", underlying: "PBR", price: "$19.00" },
  { symbol: "BILION", name: "Bilibili", underlying: "BILI", price: "$24.29" },
  { symbol: "SGOVON", name: "iShares 0-3 Month Treasury Bond ETF", underlying: "SGOV", price: "$100.94" },
  { symbol: "COHRON", name: "Coherent", underlying: "COHR", price: "$254.18" },
  { symbol: "SEDGON", name: "SolarEdge Technologies", underlying: "SEDG", price: "$51.69" },
  { symbol: "PLUGON", name: "Plug Power", underlying: "PLUG", price: "$2.27" },
  { symbol: "SCCOON", name: "Southern Copper", underlying: "SCCO", price: "$154.03" },
  { symbol: "GEMION", name: "Gemini Space Station", underlying: "GEMI", price: "$5.98" },
  { symbol: "BIDUON", name: "Baidu", underlying: "BIDU", price: "$114.75" },
  { symbol: "DASHON", name: "DoorDash", underlying: "DASH", price: "$157.61" },
  { symbol: "IVVON", name: "iShares Core S&P 500 ETF", underlying: "IVV", price: "$661.78" },
  { symbol: "CRWVON", name: "CoreWeave", underlying: "CRWV", price: "$81.35" },
  { symbol: "QCOMON", name: "Qualcomm", underlying: "QCOM", price: "$131.48" },
  { symbol: "SNAPON", name: "Snap", underlying: "SNAP", price: "$4.47" },
  { symbol: "NIOON", name: "NIO", underlying: "NIO", price: "$5.45" },
  { symbol: "AMCON", name: "AMC Entertainment", underlying: "AMC", price: "$0.9845" },
  { symbol: "TMON", name: "Toyota", underlying: "TM", price: "$210.14" },
  { symbol: "BAON", name: "Boeing", underlying: "BA", price: "$196.58" },
  { symbol: "INTUON", name: "Intuit", underlying: "INTU", price: "$459.89" },
  { symbol: "NEEON", name: "NextEra Energy", underlying: "NEE", price: "$89.97" },
  { symbol: "ENLVON", name: "Enlivex Therapeutics", underlying: "ENLV", price: "$1.03" },
  { symbol: "ARMON", name: "Arm Holdings plc", underlying: "ARM", price: "$133.38" },
  { symbol: "ABNBON", name: "Airbnb", underlying: "ABNB", price: "$129.68" },
  { symbol: "QBTSON", name: "D-Wave Quantum", underlying: "QBTS", price: "$15.81" },
  { symbol: "OKLOON", name: "Oklo", underlying: "OKLO", price: "$54.39" },
  { symbol: "NKEON", name: "Nike", underlying: "NKE", price: "$53.61" },
  { symbol: "SOFION", name: "SoFi Technologies", underlying: "SOFI", price: "$17.05" },
  { symbol: "SBUXON", name: "Starbucks", underlying: "SBUX", price: "$94.10" },
  { symbol: "FON", name: "Ford Motor", underlying: "F", price: "$11.67" },
  { symbol: "LMTON", name: "Lockheed", underlying: "LMT", price: "$634.30" },
  { symbol: "TLNON", name: "Talen Energy", underlying: "TLN", price: "$302.58" },
  { symbol: "RGTION", name: "Rigetti Computing", underlying: "RGTI", price: "$14.91" },
  { symbol: "CATON", name: "Caterpillar", underlying: "CAT", price: "$685.75" },
  { symbol: "DEON", name: "Deere", underlying: "DE", price: "$566.40" },
  { symbol: "MPON", name: "MP Materials", underlying: "MP", price: "$50.81" },
  { symbol: "IBITON", name: "iShares Bitcoin Trust", underlying: "IBIT", price: "$39.83" },
  { symbol: "ASTSON", name: "AST SpaceMobile", underlying: "ASTS", price: "$90.88" },
  { symbol: "OIHON", name: "VanEck Oil Services ETF", underlying: "OIH", price: "$383.51" },
  { symbol: "SCHWON", name: "Charles Schwab", underlying: "SCHW", price: "$94.40" },
  { symbol: "CLOION", name: "VanEck CLO ETF", underlying: "CLOI", price: "$52.84" },
  { symbol: "RDDTON", name: "Reddit", underlying: "RDDT", price: "$141.09" },
  { symbol: "TMUSON", name: "T-Mobile US", underlying: "TMUS", price: "$209.82" },
  { symbol: "SNOWON", name: "Snowflake", underlying: "SNOW", price: "$168.95" },
  { symbol: "GLXYON", name: "Galaxy Digital", underlying: "GLXY", price: "$20.62" },
  { symbol: "DBCON", name: "Invesco DB Commodity Index Tracking Fund", underlying: "DBC", price: "$28.92" },
  { symbol: "OSCRON", name: "Oscar Health", underlying: "OSCR", price: "$12.55" },
  { symbol: "GEVON", name: "GE Vernova", underlying: "GEV", price: "$871.45" },
  { symbol: "NIKLON", name: "Sprott Nickel Miners ETF", underlying: "NIKL", price: "$14.77" },
  { symbol: "URAON", name: "Global X Uranium ETF", underlying: "URA", price: "$46.65" },
  { symbol: "ONON", name: "ON Semiconductor", underlying: "ON", price: "$59.29" },
  { symbol: "GRABON", name: "Grab Holdings", underlying: "GRAB", price: "$3.55" },
  { symbol: "SOUNON", name: "SoundHound AI", underlying: "SOUN", price: "$6.55" },
  { symbol: "IONQON", name: "IonQ", underlying: "IONQ", price: "$31.41" },
  { symbol: "NBISON", name: "Nebius Group", underlying: "NBIS", price: "$118.73" },
  { symbol: "SHOPON", name: "Shopify", underlying: "SHOP", price: "$120.22" },
  { symbol: "HYGON", name: "iBoxx $ High Yield Corporate Bond ETF", underlying: "HYG", price: "$81.61" },
  { symbol: "SOON", name: "Southern", underlying: "SO", price: "$93.67" },
  { symbol: "APLDON", name: "Applied Digital", underlying: "APLD", price: "$26.06" },
  { symbol: "MRNAON", name: "Moderna", underlying: "MRNA", price: "$52.47" },
  { symbol: "LUNRON", name: "Intuitive Machines", underlying: "LUNR", price: "$17.89" },
  { symbol: "ITAON", name: "iShares US Aerospace and Defense ETF", underlying: "ITA", price: "$224.28" },
  { symbol: "XYZON", name: "Block", underlying: "XYZ", price: "$59.33" },
  { symbol: "FUTUON", name: "Futu Holdings", underlying: "FUTU", price: "$135.05" },
  { symbol: "EWJON", name: "iShares MSCI Japan ETF", underlying: "EWJ", price: "$82.30" },
  { symbol: "DGRWON", name: "WisdomTree US Quality Dividend Growth Fund", underlying: "DGRW", price: "$88.53" },
  { symbol: "FCXON", name: "Freeport-McMoRan", underlying: "FCX", price: "$52.07" },
  { symbol: "ENPHON", name: "Enphase Energy", underlying: "ENPH", price: "$43.90" },
  { symbol: "KWEBON", name: "KraneShares CSI China Internet ETF", underlying: "KWEB", price: "$28.35" },
  { symbol: "STXON", name: "Seagate", underlying: "STX", price: "$414.11" },
  { symbol: "BTGON", name: "B2Gold", underlying: "BTG", price: "$3.92" },
  { symbol: "BZON", name: "Kanzhun", underlying: "BZ", price: "$13.61" },
  { symbol: "RIVNON", name: "Rivian Automotive", underlying: "RIVN", price: "$14.92" },
  { symbol: "WFCON", name: "Wells Fargo", underlying: "WFC", price: "$79.14" },
  { symbol: "WULFON", name: "Terawulf", underlying: "WULF", price: "$15.12" },
  { symbol: "PINSON", name: "Pinterest", underlying: "PINS", price: "$19.03" },
  { symbol: "ADION", name: "Analog Devices", underlying: "ADI", price: "$311.38" },
  { symbol: "BLKON", name: "Blackrock, Inc.", underlying: "BLK", price: "$976.29" },
  { symbol: "WDCON", name: "Western Digital", underlying: "WDC", price: "$296.89" },
  { symbol: "CVNAON", name: "Carvana", underlying: "CVNA", price: "$298.72" },
  { symbol: "CMGON", name: "Chipotle", underlying: "CMG", price: "$32.77" },
  { symbol: "GEON", name: "General Electric", underlying: "GE", price: "$290.28" },
  { symbol: "OPRAON", name: "Opera", underlying: "OPRA", price: "$14.31" },
  { symbol: "AXPON", name: "American Express", underlying: "AXP", price: "$295.14" },
  { symbol: "HIMSON", name: "Hims & Hers Health", underlying: "HIMS", price: "$22.09" },
  { symbol: "SPOTON", name: "Spotify", underlying: "SPOT", price: "$479.27" },
  { symbol: "PCGON", name: "PG&E", underlying: "PCG", price: "$18.59" },
  { symbol: "KLACON", name: "KLA", underlying: "KLAC", price: "$1,497.45" },
  { symbol: "CIBRON", name: "First Trust NASDAQ Cybersecurity ETF", underlying: "CIBR", price: "$64.71" },
  { symbol: "COFON", name: "Capital One", underlying: "COF", price: "$177.93" },
  { symbol: "EQIXON", name: "Equinix", underlying: "EQIX", price: "$949.61" },
  { symbol: "VTVON", name: "Vanguard Value ETF", underlying: "VTV", price: "$197.36" },
  { symbol: "CAPRON", name: "Capricor Therapeutics", underlying: "CAPR", price: "$31.12" },
  { symbol: "FSOLON", name: "Fidelity Solana Fund", underlying: "FSOL", price: "$10.54" },
  { symbol: "VFSON", name: "VinFast Auto", underlying: "VFS", price: "$2.85" },
  { symbol: "VRTXON", name: "Vertex Pharmaceuticals", underlying: "VRTX", price: "$456.11" },
  { symbol: "INCEON", name: "Franklin Income Equity Focus ETF", underlying: "INCE", price: "$64.33" },
  { symbol: "FLHYON", name: "Franklin High Yield Corporate ETF", underlying: "FLHY", price: "$24.10" },
  { symbol: "WMON", name: "Waste Management", underlying: "WM", price: "$234.12" },
  { symbol: "ETNON", name: "Eaton", underlying: "ETN", price: "$363.02" },
  { symbol: "GLTRON", name: "abrdn Physical Precious Metals Basket Shares ETF", underlying: "GLTR", price: "$209.72" },
  { symbol: "IEFON", name: "iShares 7-10 Year Treasury Bond ETF", underlying: "IEF", price: "$95.53" },
  { symbol: "SHYON", name: "iShares 1-3 Year Treasury Bond ETF", underlying: "SHY", price: "$82.29" },
  { symbol: "HYSON", name: "PIMCO 0-5 Year High Yield Corporate Bond Index ETF", underlying: "HYS", price: "$93.14" },
  { symbol: "FFOGON", name: "Franklin Focused Growth ETF", underlying: "FFOG", price: "$41.97" },
  { symbol: "FLQLON", name: "Franklin US Large Cap Multifactor Index ETF", underlying: "FLQL", price: "$67.72" },
  { symbol: "PAVEON", name: "Global X US Infrastructure Development ETF", underlying: "PAVE", price: "$50.38" },
  { symbol: "FGDLON", name: "Franklin Responsibly Sourced Gold ETF", underlying: "FGDL", price: "$61.04" },
  { symbol: "NOCON", name: "Northrop Grumman", underlying: "NOC", price: "$717.63" },
  { symbol: "QUBTON", name: "Quantum Computing", underlying: "QUBT", price: "$7.23" },
  { symbol: "UNPON", name: "Union Pacific Corporation", underlying: "UNP", price: "$233.92" },
  { symbol: "ETHAON", name: "iShares Ethereum Trust", underlying: "ETHA", price: "$16.19" },
  { symbol: "EXODON", name: "Exodus Movement", underlying: "EXOD", price: "$7.61" },
  { symbol: "REGNON", name: "Regeneron Pharmaceuticals", underlying: "REGN", price: "$743.13" },
  { symbol: "IWNON", name: "iShares Russell 2000 Value ETF", underlying: "IWN", price: "$189.75" },
  { symbol: "MTZON", name: "MasTec", underlying: "MTZ", price: "$312.24" },
  { symbol: "APOON", name: "Apollo Global Management", underlying: "APO", price: "$111.92" },
  { symbol: "FTGCON", name: "First Trust Global Tactical Commodity Strategy Fund", underlying: "FTGC", price: "$28.67" },
  { symbol: "IJHON", name: "iShares Core S&P MidCap ETF", underlying: "IJH", price: "$68.25" },
  { symbol: "SOXXON", name: "iShares Semiconductor ETF", underlying: "SOXX", price: "$334.21" },
  { symbol: "ANETON", name: "Arista Networks", underlying: "ANET", price: "$132.23" },
  { symbol: "CON", name: "Citigroup", underlying: "C", price: "$110.73" },
  { symbol: "ACHRON", name: "Archer Aviation", underlying: "ACHR", price: "$5.77" },
  { symbol: "ISRGON", name: "Intuitive Surgical", underlying: "ISRG", price: "$477.75" },
  { symbol: "ECHON", name: "iShares MSCI Chile ETF", underlying: "ECH", price: "$39.29" },
  { symbol: "TXNON", name: "Texas Instruments", underlying: "TXN", price: "$190.37" },
  { symbol: "JAAAON", name: "Janus Henderson AAA CLO ETF", underlying: "JAAA", price: "$50.79" },
  { symbol: "FXION", name: "iShares China Large-Cap ETF", underlying: "FXI", price: "$35.19" },
  { symbol: "BINCON", name: "iShares Flexible Income Active ETF", underlying: "BINC", price: "$52.51" },
  { symbol: "LOWON", name: "Lowe's", underlying: "LOW", price: "$228.67" },
  { symbol: "UBERON", name: "Uber", underlying: "UBER", price: "$74.44" },
  { symbol: "EWZON", name: "iShares MSCI Brazil ETF", underlying: "EWZ", price: "$35.64" },
  { symbol: "ITOTON", name: "iShares Core S&P Total US Stock Market ETF", underlying: "ITOT", price: "$143.75" },
  { symbol: "INDAON", name: "iShares MSCI India ETF", underlying: "INDA", price: "$46.55" },
  { symbol: "NEMON", name: "Newmont", underlying: "NEM", price: "$95.29" },
  { symbol: "LION", name: "Li Auto", underlying: "LI", price: "$16.56" },
  { symbol: "VNQON", name: "Vanguard Real Estate ETF", underlying: "VNQ", price: "$88.95" },
  { symbol: "IWFON", name: "iShares Russell 1000 Growth ETF", underlying: "IWF", price: "$435.80" },
  { symbol: "NTESON", name: "NetEase", underlying: "NTES", price: "$116.59" },
  { symbol: "RTXON", name: "RTX", underlying: "RTX", price: "$200.86" },
  { symbol: "USFRON", name: "WisdomTree Floating Rate Treasury Fund", underlying: "USFR", price: "$48.17" },
  { symbol: "ALBON", name: "Albemarle", underlying: "ALB", price: "$156.42" },
  { symbol: "CPNGON", name: "Coupang", underlying: "CPNG", price: "$18.94" },
  { symbol: "UECON", name: "Uranium Energy", underlying: "UEC", price: "$12.04" },
  { symbol: "AMGNON", name: "Amgen", underlying: "AMGN", price: "$342.44" },
  { symbol: "COSTON", name: "Costco", underlying: "COST", price: "$981.14" },
  { symbol: "AGGON", name: "iShares Core US Aggregate Bond ETF", underlying: "AGG", price: "$100.74" },
  { symbol: "BLSHON", name: "Bullish", underlying: "BLSH", price: "$38.44" },
  { symbol: "GRNDON", name: "Grindr", underlying: "GRND", price: "$12.58" },
  { symbol: "TCOMON", name: "Trip.com Group", underlying: "TCOM", price: "$51.80" },
  { symbol: "SPGION", name: "S&P Global", underlying: "SPGI", price: "$427.09" },
  { symbol: "CIFRON", name: "Cipher Mining", underlying: "CIFR", price: "$14.03" },
  { symbol: "TON", name: "AT&T", underlying: "T", price: "$28.49" },
  { symbol: "TIPON", name: "iShares TIPS Bond ETF", underlying: "TIP", price: "$112.06" },
  { symbol: "VZON", name: "Verizon", underlying: "VZ", price: "$49.66" },
];
