/**
 * Maps perpetual market stock tickers to their tokenized counterparts
 * available on Jupiter (Solana) via Backed Finance xStocks.
 *
 * When a user clicks a stock market in the perps list, they are routed
 * to the Swap page pre-filled with the corresponding xStock symbol so
 * they can buy the tokenized equity via Jupiter.
 *
 * Keys: base asset ticker as it appears in the perp market (e.g. "TSLA")
 * Values: the exact Jupiter/xStock token symbol to pre-select in Swap
 */
export const STOCK_SWAP_MAP: Record<string, string> = {
  TSLA:   "xTSLA",
  NVDA:   "xNVDA",
  AAPL:   "xAAPL",
  MSFT:   "xMSFT",
  META:   "xMETA",
  GOOGL:  "xGOOGL",
  GOOG:   "xGOOGL",
  AMZN:   "xAMZN",
  COIN:   "xCOIN",
  MSTR:   "xMSTR",
  PLTR:   "xPLTR",
  HOOD:   "xHOOD",
  AMD:    "xAMD",
  NFLX:   "xNFLX",
  INTC:   "xINTC",
  MU:     "xMU",
  ORCL:   "xORCL",
  SNAP:   "xSNAP",
  BABA:   "xBABA",
  TSM:    "xTSM",
  RIVN:   "xRIVN",
  PTON:   "xPTON",
  CVNA:   "xCVNA",
  NKE:    "xNKE",
  DIS:    "xDIS",
  ABNB:   "xABNB",
  UBER:   "xUBER",
  LYFT:   "xLYFT",
  SHOP:   "xSHOP",
  PYPL:   "xPYPL",
  SQ:     "xSQ",
  RBLX:   "xRBLX",
  SPOT:   "xSPOT",
  TWLO:   "xTWLO",
  ZM:     "xZM",
  CRWD:   "xCRWD",
  DDOG:   "xDDOG",
  NET:    "xNET",
  SNOW:   "xSNOW",
  PANW:   "xPANW",
  FTNT:   "xFTNT",
  NOW:    "xNOW",
  CRM:    "xCRM",
  ORCL2:  "xORCL",
  ADBE:   "xADBE",
  QCOM:   "xQCOM",
  AVGO:   "xAVGO",
  TXN:    "xTXN",
  ARM:    "xARM",
  SMCI:   "xSMCI",
  DELL:   "xDELL",
  HPQ:    "xHPQ",
  IBM:    "xIBM",
  CSCO:   "xCSCO",
  ORCAI:  "xORCL",
  INTU:   "xINTU",
  ASML:   "xASML",
  MRVL:   "xMRVL",
  KLAC:   "xKLAC",
  LRCX:   "xLRCX",
  AMAT:   "xAMAT",
  MPWR:   "xMPWR",
  JPM:    "xJPM",
  BAC:    "xBAC",
  WFC:    "xWFC",
  GS:     "xGS",
  MS:     "xMS",
  C:      "xC",
  BRK:    "xBRKB",
  BRKB:   "xBRKB",
  V:      "xV",
  MA:     "xMA",
  AXP:    "xAXP",
  KO:     "xKO",
  PEP:    "xPEP",
  MCD:    "xMCD",
  SBUX:   "xSBUX",
  WMT:    "xWMT",
  COST:   "xCOST",
  TGT:    "xTGT",
  HD:     "xHD",
  LOW:    "xLOW",
  CVX:    "xCVX",
  XOM:    "xXOM",
  PFE:    "xPFE",
  MRNA:   "xMRNA",
  JNJ:    "xJNJ",
  LLY:    "xLLY",
  ABBV:   "xABBV",
  UNH:    "xUNH",
  AMGN:   "xAMGN",
  GILD:   "xGILD",
  PG:     "xPG",
  MMM:    "xMMM",
  BA:     "xBA",
  CAT:    "xCAT",
  GE:     "xGE",
  HON:    "xHON",
  RTX:    "xRTX",
  LMT:    "xLMT",
  NOC:    "xNOC",
  NFLX2:  "xNFLX",
  PARA:   "xPARA",
  T:      "xT",
  VZ:     "xVZ",
  TMUS:   "xTMUS",
  GLXY:   "xGLXY",
  HOOD2:  "xHOOD",
  CRCL:   "xCRCL",
  SOUN:   "xSOUN",
  ACHR:   "xACHR",
  JOBY:   "xJOBY",
  IONQ:   "xIONQ",
  RGTI:   "xRGTI",
  QUBT:   "xQUBT",
  OKLO:   "xOKLO",
  NNE:    "xNNE",
  SMR:    "xSMR",
  SYM:    "xSYM",
  BMNR:   "xBMNR",
  SERV:   "xSERV",
  AI:     "xAI",
  BBAI:   "xBBAI",
  SNDG:   "xSNDG",
  KULR:   "xKULR",
  MANU:   "xMANU",
  BYD:    "xBYD",
  NIO:    "xNIO",
  XPEV:   "xXPEV",
  LI:     "xLI",
  HANMI:  "xHANMI",
};

/**
 * Returns true if the given base asset ticker has a known tokenized
 * equivalent available to buy on Jupiter (Solana).
 */
export function hasStockSwap(baseAsset: string): boolean {
  return baseAsset.toUpperCase() in STOCK_SWAP_MAP;
}

/**
 * Returns the Jupiter token symbol to pre-select in Swap for the given
 * stock ticker, or undefined if not mapped.
 */
export function getStockSwapSymbol(baseAsset: string): string | undefined {
  return STOCK_SWAP_MAP[baseAsset.toUpperCase()];
}
